-- 1. Total revenue generated by male vs female customers
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;
-- 2. Customers who used a discount but still spent more than the average purchase amount
SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer
  );
  -- 3. Average purchase amount: Standard vs Express shipping
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
-- 4. Do subscribed customers spend more?
SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue,
    COUNT(customer_id) AS total_customers
FROM customer
GROUP BY subscription_status;
-- 5. Segment customers into New, Recurring, and Loyal
SELECT 
    customer_id,
    previous_purchases,
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Recurring'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END AS customer_segment
FROM customer;
-- 6. Are repeat buyers more likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type,
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
GROUP BY 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END,
    subscription_status;
	-- 7. Revenue contribution of each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 / 
        (SELECT SUM(purchase_amount) FROM customer), 
        2
    ) AS revenue_percentage
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
-- 8. Age group with the highest average purchase amount
SELECT 
    age_group,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
GROUP BY age_group
ORDER BY avg_purchase_amount DESC
LIMIT 1;
-- 10. Distribution of previous purchases among customers
SELECT 
    previous_purchases,
    COUNT(customer_id) AS customer_count
FROM customer
GROUP BY previous_purchases
ORDER BY previous_purchases;
-- 11. Top 10 customers by total spending
SELECT 
    customer_id,
    SUM(purchase_amount) AS total_spending
FROM customer
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 10;

-- 12. Classify customers into High, Medium, and Low Value segments
SELECT 
    customer_id,
    SUM(purchase_amount) AS total_spending,
    SUM(previous_purchases) AS total_previous_purchases,
    CASE
        WHEN SUM(purchase_amount) >= 200 
             AND SUM(previous_purchases) > 10 THEN 'High Value'
        WHEN SUM(purchase_amount) BETWEEN 100 AND 199
             OR SUM(previous_purchases) BETWEEN 5 AND 10 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS value_segment
FROM customer
GROUP BY customer_id;
